name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev
      
    - name: Build project
      run: make
      
    - name: Verify artifacts
      run: |
        [ -f app/fnaf ] || exit 1
        [ -f app/Nights.db ] || exit 1
